package com.go.demo.model.repository;

import com.go.demo.model.AccountHolder;
import com.go.demo.model.repository.factory.CustomRepository;
import org.springframework.data.querydsl.QueryDslPredicateExecutor;

/** 
 * Spring Data Repository for table: account_holder.
 * @author autogenerated/custom
 */ 
public interface AccountHolderRepository extends CustomRepository<AccountHolder, Long>, QueryDslPredicateExecutor<AccountHolder> {

	// Add any extra methods here. This file will not get overwritten unlike any other generated file
}
